x-common-variables: &common-variables
  DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  AWS_REGION:
  AWS_BUCKET_NAME:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      <<: *common-variables
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    restart:
      always
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: