[tool.ruff]
src = ["products_admin"]
target-version = "py311"
line-length = 110
fix = true

[tool.ruff.lint]
select = ["E", "F", "W", "C", "D", "I", "N", "Q"]
ignore = ["D203", "D213", "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D400", "D415"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D", "E501"]
"migrations/*.py" = ["ALL"]
"products_admin/settings.py" = ["ALL"]
