# Generated by Django 5.1.5 on 2025-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
