# Generated by Django 5.1.5 on 2025-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_photo_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
